/*
 * Mad-Advertisement
 * Copyright (C) 2011-2013 Thorsten Marx <thmarx@gmx.net>
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 * 	http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 */
"undefined"==typeof madApi&&(madApi={insetScript:function(b){var a=document.createElement("script");a.type="text/javascript";a.async=!0;a.src=b;(document.getElementsByTagName("head")[0]||document.body).appendChild(a)},onload:function(b){var a=window.onload;window.onload="function"!=typeof window.onload?b:function(){a();b()}},delegate:function(b,a,d){var c=d||arguments,e=function(){return b.apply(arguments.callee.target,c)};e.target=a;e.func=this;return e},position:function(b){var a=0,d=0;if(b.offsetParent){do a+=
b.offsetLeft,d+=b.offsetTop;while(b=b.offsetParent)}return{left:a,top:d}},size:function(b){return{height:b.offsetHeight,width:b.offsetWidth}},isIE:function(b){return 0<window.navigator.userAgent.indexOf("MSIE ")?!0:!1},isBrowser:function(b,a){versionOk=browserOk=!1;browserOk=-1!=navigator.appName.indexOf(b);versionOk=0==a?!0:a<=parseInt(navigator.appVersion);return browserOk&&versionOk},getWindowSize:function(){var b=0,a=0;if("number"==typeof window.innerWidth)b=window.innerWidth,a=window.innerHeight;
else if(document.documentElement&&(document.documentElement.clientWidth||document.documentElement.clientHeight))b=document.documentElement.clientWidth,a=document.documentElement.clientHeight;else if(document.body&&(document.body.clientWidth||document.body.clientHeight))b=document.body.clientWidth,a=document.body.clientHeight;return{width:b,height:a}},getScrollXY:function(b){var a=b=0;if("number"==typeof window.pageYOffset)a=window.pageYOffset,b=window.pageXOffset;else if(document.body&&(document.body.scrollLeft||
document.body.scrollTop))a=document.body.scrollTop,b=document.body.scrollLeft;else if(document.documentElement&&(document.documentElement.scrollLeft||document.documentElement.scrollTop))a=document.documentElement.scrollTop,b=document.documentElement.scrollLeft;return{x:b,y:a}},addEvent:function(b,a,d,c){b.attachEvent?b.attachEvent("on"+a,d):(c||(c=!1),b.addEventListener(a,d,c))},flash:function(b,a){var d=0;if("object"==typeof navigator.plugins["Shockwave Flash"])d=navigator.plugins["Shockwave Flash"].description,
d=d.substr(16,d.indexOf(".",16)-16);else if("function"==typeof ActiveXObject)for(var c=2;c<a+1;c++)try{"object"==typeof new ActiveXObject("ShockwaveFlash.ShockwaveFlash."+c)&&(d=c)}catch(e){}return{available:d,required:b}},fx:function(b){var a=null;if(b.nodeType&&1==b.nodeType)a=b;else if(String(b).match(/^#([^$]+)$/i)){if(a=document.getElementById(RegExp.$1+""),!a)return null}else return null;if("undefined"!=typeof a._fx&&a._fx)return a._fx._addSet(),a;a.fxVersion=0.1;a._fx={};a._fx.sets=[];a._fx._currSet=
0;if("undefined"!=typeof a._fxTerminated)try{delete a._fxTerminated}catch(d){a._fxTerminated=null}var c={"left|top|right|bottom|width|height|margin|padding|spacing|backgroundx|backgroundy":"px",font:"pt",opacity:""},e=!!navigator.userAgent.match(/MSIE/ig),g={delay:100,step:5,unit:""},h={opacity:function(f,b){f=parseInt(f);if(isNaN(f)){if(e){var l=/alpha\s*\(opacity\s*=\s*(\d+)\)/.exec(a.style.filter+"");return l?parseInt(l[1]):1}return Math.round(100*(a.style.opacity?parseFloat(a.style.opacity):1))}f=
Math.min(100,Math.max(0,f));e?(a.style.zoom=1,a.style.filter="alpha(opacity\x3d"+f+");"):a.style.opacity=f/100},backgroundx:function(f,b){f=parseInt(f);var l=0,d=0,c=/^(-?\d+)[^\d\-]+(-?\d+)/.exec(a.style.backgroundPosition+"");c&&(l=parseInt(c[1]),d=parseInt(c[2]));if(isNaN(f))return l;a.style.backgroundPosition=f+b+" "+d+b},backgroundy:function(f,b){f=parseInt(f);var l=0,d=0,c=/^(-?\d+)[^\d\-]+(-?\d+)/.exec(a.style.backgroundPosition+"");c&&(l=parseInt(c[1]),d=parseInt(c[2]));if(isNaN(f))return d;
a.style.backgroundPosition=l+b+" "+f+b}},m={width:function(){return parseInt(a.offsetWidth)},height:function(){return parseInt(a.offsetHeight)},left:function(){for(var f=0,b=a;b;b=b.offsetParent)f+=parseInt(b.offsetLeft);return f},top:function(){for(var f=0,b=a;b;b=b.offsetParent)f+=parseInt(b.offsetTop);return f}};a.fxAddSet=function(){this._fx._addSet();return this};a.fxHold=function(f,b){if(a._fx.sets[this._fx._currSet]._isrunning)return this;b=parseInt(b);this._fx.sets[isNaN(b)?this._fx._currSet:
b]._holdTime=f;return this};a.fxAdd=function(a){var b=this._fx._currSet;if(this._fx.sets[b]._isrunning)return this;for(var d in g)a[d]||(a[d]=g[d]);if(!a.unit)for(var k in c)if(RegExp(k,"i").test(a.type)){a.unit=c[k];break}a.onstart=a.onstart&&a.onstart.call?a.onstart:function(){};a.onfinish=a.onfinish&&a.onfinish.call?a.onfinish:function(){};if(!this._fx[a.type])if(h[a.type])this._fx[a.type]=h[a.type];else{var e=this;this._fx[a.type]=function(b,d){if("undefined"==typeof b)return parseInt(e.style[a.type]);
e.style[a.type]=parseInt(b)+d}}isNaN(a.from)&&(isNaN(this._fx[a.type]())?a.from=m[a.type]?m[a.type]():0:a.from=this._fx[a.type]());a._initial=a.from;this._fx[a.type](a.from,a.unit);this._fx.sets[b]._queue.push(a);return this};a.fxRun=function(b,d,c){var k=a._fx._currSet;if(this._fx.sets[k]._isrunning)return this;setTimeout(function(){if(a._fx.sets[k]._isrunning)return a;a._fx.sets[k]._isrunning=!0;if(0<a._fx.sets[k]._effectsDone)return a;a._fx.sets[k]._onfinal=b&&b.call?b:function(){};a._fx.sets[k]._onloop=
c&&c.call?c:function(){};isNaN(d)||(a._fx.sets[k]._loops=d);for(var e=0;e<a._fx.sets[k]._queue.length;e++)a._fx.sets[k]._queue[e].onstart.call(a),a._fx._process(k,e)},a._fx.sets[k]._holdTime);return this};a.fxPause=function(a,b){this._fx.sets[!isNaN(b)?b:this._fx._currSet]._paused=a;return this};a.fxStop=function(a){this._fx.sets[!isNaN(a)?a:this._fx._currSet]._stoped=!0;return this};a.fxReset=function(){for(var a=0;a<this._fx.sets.length;a++)for(var b=0;b<this._fx.sets[a]._queue.length;b++){var d=
this._fx.sets[a]._queue[b];if(isNaN(d._initial))this._fx[d.type]("","");else this._fx[d.type](d._initial,d.unit)}b="_fx fxHold fxAdd fxAddSet fxRun fxPause fxStop fxReset".split(" ");for(a=0;a<b.length;a++)try{delete this[b[a]]}catch(c){this[b[a]]=null}this._fxTerminated=!0};a._fx._addSet=function(){var a=this.sets.length;this._currSet=a;this.sets[a]={};this.sets[a]._loops=1;this.sets[a]._stoped=!1;this.sets[a]._queue=[];this.sets[a]._effectsDone=0;this.sets[a]._loopsDone=0;this.sets[a]._holdTime=
0;this.sets[a]._paused=!1;this.sets[a]._isrunning=!1;this.sets[a]._onfinal=function(){};return this};a._fx._process=function(b,d){if(this.sets[b]&&!this.sets[b]._stoped&&!a._fxTerminated){var c=this.sets[b]._queue[d],e=this[c.type]();if(0<c.step&&e+c.step<=c.to||0>c.step&&e+c.step>=c.to){if(!this.sets[b]._paused)this[c.type](e+c.step,c.unit);var g=this;setTimeout(function(){g._process&&g._process(b,d)},c.delay)}else if(this[c.type](c.to,c.unit),this.sets[b]._effectsDone++,c.onfinish.call(a),this.sets[b]._queue.length==
this.sets[b]._effectsDone)if(this.sets[b]._effectsDone=0,this.sets[b]._loopsDone++,this.sets[b]._onloop.call(a,this.sets[b]._loopsDone),this.sets[b]._loopsDone<this.sets[b]._loops||-1==this.sets[b]._loops)for(e=0;e<this.sets[b]._queue.length;e++)this[c.type](c.from,this.sets[b]._queue[e].unit),this.sets[b]._queue[e].onstart.call(a,this.sets[b]._loopsDone),this._process(b,e);else this.sets[b]._onfinal.call(a)}};a._fx._addSet();return a},ajax:{getHTTPObject:function(){var b=!1;if("undefined"!=typeof ActiveXObject)try{b=
new ActiveXObject("Msxml2.XMLHTTP")}catch(a){try{b=new ActiveXObject("Microsoft.XMLHTTP")}catch(d){b=!1}}else if(window.XMLHttpRequest)try{b=new XMLHttpRequest}catch(c){b=!1}return b},load:function(b,a,d,c,e){var g=this.init();if(g&&b){g.overrideMimeType&&g.overrideMimeType("text/xml");c||(c="GET");d||(d="text");e||(e={});d=d.toLowerCase();c=c.toUpperCase();var h="uid\x3d"+(new Date).getTime();b+=b.indexOf("?")+1?"\x26":"?";b+=h;h=null;"POST"==c&&(h=b.split("?"),b=h[0],h=h[1]);g.open(c,b,!0);"POST"==
c&&(g.setRequestHeader("Content-type","application/x-www-form-urlencoded"),g.setRequestHeader("Content-length",h.length),g.setRequestHeader("Connection","close"));g.onreadystatechange=e.handler?function(){e.handler(g)}:function(){if(4==g.readyState)if(200==g.status){var b="";g.responseText&&(b=g.responseText);"j"==d.charAt(0)?(b=b.replace(/[\n\r]/g,""),b=eval("("+b+")")):"x"==d.charAt(0)&&(b=g.responseXML);a&&a(b)}else e.loadingIndicator&&document.getElementsByTagName("body")[0].removeChild(e.loadingIndicator),
e.loading&&(document.getElementById(e.loading).style.display="none"),error&&error(g.status)};g.send(h)}},bind:function(b){var a={url:"",onSuccess:!1,onError:!1,format:"text",method:"GET",update:"",loading:"",loadingIndicator:""},d;for(d in a)b[d]&&(a[d]=b[d]);if(a.url){var c=!1;a.loadingIndicator&&(c=document.createElement("div"),c.setAttribute("style","position:absolute;top:0px;left:0px;"),c.setAttribute("class","loading-indicator"),c.innerHTML=a.loadingIndicator,document.getElementsByTagName("body")[0].appendChild(c),
this.opt.loadingIndicator=c);a.loading&&(document.getElementById(a.loading).style.display="block");this.load(a.url,function(b){if(a.onSuccess)a.onSuccess(b);a.update&&(document.getElementById(a.update).innerHTML=b);c&&document.getElementsByTagName("body")[0].removeChild(c);a.loading&&(document.getElementById(a.loading).style.display="none")},a.format,a.method,a)}},init:function(){return this.getHTTPObject()}}});
function mad_expandableImage_open(b,a){if(0==document.getElementById(a).style.opacity){var d=madApi.position(document.getElementById(b)),c=madApi.size(document.getElementById(b)),e=madApi.getWindowSize(),g,h;g=d.top;h=d.left+c.width;300>e.width-(d.left+c.width)&&(g=d.top,h=d.left-300);document.getElementById(a).style.left=h+"px";document.getElementById(a).style.top=g+"px";madApi.isIE(0)?document.getElementById(a).style.opacity=1:madApi.fx(document.getElementById(a)).fxAdd({type:"opacity",from:0,to:100,
step:10,delay:10}).fxRun(null,1)}}function mad_expandableImage_close(b){0!=document.getElementById(b).style.opacity&&(madApi.isIE(0)?document.getElementById(b).style.opacity=0:madApi.fx(document.getElementById(b)).fxAdd({type:"opacity",from:100,to:0,step:10,delay:10}).fxRun(null,1))};