"undefined"==typeof madApi&&(madApi={insertScript:function(b){var a=document.createElement("script");a.type="text/javascript";a.async=!0;a.src=b;(document.getElementsByTagName("head")[0]||document.body).appendChild(a)},serialize:function(b){var a=[],c;for(c in b)b.hasOwnProperty(c)&&a.push("kv_"+encodeURIComponent(c)+"\x3d"+encodeURIComponent(b[c]));return a.join("\x26")},onload:function(b){var a=window.onload;window.onload="function"!=typeof window.onload?b:function(){a();b()}},delegate:function(b,
a,c){var d=c||arguments,f=function(){return b.apply(arguments.callee.target,d)};f.target=a;f.func=this;return f},position:function(b){var a=0,c=0;if(b.offsetParent){do a+=b.offsetLeft,c+=b.offsetTop;while(b=b.offsetParent)}return{left:a,top:c}},size:function(b){return{height:b.offsetHeight,width:b.offsetWidth}},isIE:function(b){return 0<window.navigator.userAgent.indexOf("MSIE ")?!0:!1},isBrowser:function(b,a){versionOk=browserOk=!1;browserOk=-1!=navigator.appName.indexOf(b);versionOk=0==a?!0:a<=
parseInt(navigator.appVersion);return browserOk&&versionOk},getWindowSize:function(){var b=0,a=0;if("number"==typeof window.innerWidth)b=window.innerWidth,a=window.innerHeight;else if(document.documentElement&&(document.documentElement.clientWidth||document.documentElement.clientHeight))b=document.documentElement.clientWidth,a=document.documentElement.clientHeight;else if(document.body&&(document.body.clientWidth||document.body.clientHeight))b=document.body.clientWidth,a=document.body.clientHeight;
return{width:b,height:a}},getScrollXY:function(b){var a=b=0;if("number"==typeof window.pageYOffset)a=window.pageYOffset,b=window.pageXOffset;else if(document.body&&(document.body.scrollLeft||document.body.scrollTop))a=document.body.scrollTop,b=document.body.scrollLeft;else if(document.documentElement&&(document.documentElement.scrollLeft||document.documentElement.scrollTop))a=document.documentElement.scrollTop,b=document.documentElement.scrollLeft;return{x:b,y:a}},addEvent:function(b,a,c,d){b.attachEvent?
b.attachEvent("on"+a,c):(d||(d=!1),b.addEventListener(a,c,d))},flash:function(b,a){var c=0;if("object"==typeof navigator.plugins["Shockwave Flash"])c=navigator.plugins["Shockwave Flash"].description,c=c.substr(16,c.indexOf(".",16)-16);else if("function"==typeof ActiveXObject)for(var d=2;d<a+1;d++)try{"object"==typeof new ActiveXObject("ShockwaveFlash.ShockwaveFlash."+d)&&(c=d)}catch(f){}return{available:c,required:b}},fx:function(b){var a=null;if(b.nodeType&&1==b.nodeType)a=b;else if(String(b).match(/^#([^$]+)$/i)){if(a=
document.getElementById(RegExp.$1+""),!a)return null}else return null;if("undefined"!=typeof a._fx&&a._fx)return a._fx._addSet(),a;a.fxVersion=0.1;a._fx={};a._fx.sets=[];a._fx._currSet=0;if("undefined"!=typeof a._fxTerminated)try{delete a._fxTerminated}catch(c){a._fxTerminated=null}var d={"left|top|right|bottom|width|height|margin|padding|spacing|backgroundx|backgroundy":"px",font:"pt",opacity:""},f=!!navigator.userAgent.match(/MSIE/ig),e={delay:100,step:5,unit:""},h={opacity:function(g,b){g=parseInt(g);
if(isNaN(g)){if(f){var c=/alpha\s*\(opacity\s*=\s*(\d+)\)/.exec(a.style.filter+"");return c?parseInt(c[1]):1}return Math.round(100*(a.style.opacity?parseFloat(a.style.opacity):1))}g=Math.min(100,Math.max(0,g));f?(a.style.zoom=1,a.style.filter="alpha(opacity\x3d"+g+");"):a.style.opacity=g/100},backgroundx:function(g,b){g=parseInt(g);var c=0,d=0,e=/^(-?\d+)[^\d\-]+(-?\d+)/.exec(a.style.backgroundPosition+"");e&&(c=parseInt(e[1]),d=parseInt(e[2]));if(isNaN(g))return c;a.style.backgroundPosition=g+b+
" "+d+b},backgroundy:function(g,b){g=parseInt(g);var c=0,d=0,e=/^(-?\d+)[^\d\-]+(-?\d+)/.exec(a.style.backgroundPosition+"");e&&(c=parseInt(e[1]),d=parseInt(e[2]));if(isNaN(g))return d;a.style.backgroundPosition=c+b+" "+g+b}},l={width:function(){return parseInt(a.offsetWidth)},height:function(){return parseInt(a.offsetHeight)},left:function(){for(var g=0,b=a;b;b=b.offsetParent)g+=parseInt(b.offsetLeft);return g},top:function(){for(var g=0,b=a;b;b=b.offsetParent)g+=parseInt(b.offsetTop);return g}};
a.fxAddSet=function(){this._fx._addSet();return this};a.fxHold=function(g,b){if(a._fx.sets[this._fx._currSet]._isrunning)return this;b=parseInt(b);this._fx.sets[isNaN(b)?this._fx._currSet:b]._holdTime=g;return this};a.fxAdd=function(a){var b=this._fx._currSet;if(this._fx.sets[b]._isrunning)return this;for(var c in e)a[c]||(a[c]=e[c]);if(!a.unit)for(var k in d)if(RegExp(k,"i").test(a.type)){a.unit=d[k];break}a.onstart=a.onstart&&a.onstart.call?a.onstart:function(){};a.onfinish=a.onfinish&&a.onfinish.call?
a.onfinish:function(){};if(!this._fx[a.type])if(h[a.type])this._fx[a.type]=h[a.type];else{var f=this;this._fx[a.type]=function(b,c){if("undefined"==typeof b)return parseInt(f.style[a.type]);f.style[a.type]=parseInt(b)+c}}isNaN(a.from)&&(isNaN(this._fx[a.type]())?a.from=l[a.type]?l[a.type]():0:a.from=this._fx[a.type]());a._initial=a.from;this._fx[a.type](a.from,a.unit);this._fx.sets[b]._queue.push(a);return this};a.fxRun=function(b,c,d){var e=a._fx._currSet;if(this._fx.sets[e]._isrunning)return this;
setTimeout(function(){if(a._fx.sets[e]._isrunning)return a;a._fx.sets[e]._isrunning=!0;if(0<a._fx.sets[e]._effectsDone)return a;a._fx.sets[e]._onfinal=b&&b.call?b:function(){};a._fx.sets[e]._onloop=d&&d.call?d:function(){};isNaN(c)||(a._fx.sets[e]._loops=c);for(var f=0;f<a._fx.sets[e]._queue.length;f++)a._fx.sets[e]._queue[f].onstart.call(a),a._fx._process(e,f)},a._fx.sets[e]._holdTime);return this};a.fxPause=function(a,b){this._fx.sets[!isNaN(b)?b:this._fx._currSet]._paused=a;return this};a.fxStop=
function(a){this._fx.sets[!isNaN(a)?a:this._fx._currSet]._stoped=!0;return this};a.fxReset=function(){for(var a=0;a<this._fx.sets.length;a++)for(var b=0;b<this._fx.sets[a]._queue.length;b++){var c=this._fx.sets[a]._queue[b];if(isNaN(c._initial))this._fx[c.type]("","");else this._fx[c.type](c._initial,c.unit)}b="_fx fxHold fxAdd fxAddSet fxRun fxPause fxStop fxReset".split(" ");for(a=0;a<b.length;a++)try{delete this[b[a]]}catch(d){this[b[a]]=null}this._fxTerminated=!0};a._fx._addSet=function(){var a=
this.sets.length;this._currSet=a;this.sets[a]={};this.sets[a]._loops=1;this.sets[a]._stoped=!1;this.sets[a]._queue=[];this.sets[a]._effectsDone=0;this.sets[a]._loopsDone=0;this.sets[a]._holdTime=0;this.sets[a]._paused=!1;this.sets[a]._isrunning=!1;this.sets[a]._onfinal=function(){};return this};a._fx._process=function(b,c){if(this.sets[b]&&!this.sets[b]._stoped&&!a._fxTerminated){var d=this.sets[b]._queue[c],e=this[d.type]();if(0<d.step&&e+d.step<=d.to||0>d.step&&e+d.step>=d.to){if(!this.sets[b]._paused)this[d.type](e+
d.step,d.unit);var f=this;setTimeout(function(){f._process&&f._process(b,c)},d.delay)}else if(this[d.type](d.to,d.unit),this.sets[b]._effectsDone++,d.onfinish.call(a),this.sets[b]._queue.length==this.sets[b]._effectsDone)if(this.sets[b]._effectsDone=0,this.sets[b]._loopsDone++,this.sets[b]._onloop.call(a,this.sets[b]._loopsDone),this.sets[b]._loopsDone<this.sets[b]._loops||-1==this.sets[b]._loops)for(e=0;e<this.sets[b]._queue.length;e++)this[d.type](d.from,this.sets[b]._queue[e].unit),this.sets[b]._queue[e].onstart.call(a,
this.sets[b]._loopsDone),this._process(b,e);else this.sets[b]._onfinal.call(a)}};a._fx._addSet();return a},ajax:{getHTTPObject:function(){var b=!1;if("undefined"!=typeof ActiveXObject)try{b=new ActiveXObject("Msxml2.XMLHTTP")}catch(a){try{b=new ActiveXObject("Microsoft.XMLHTTP")}catch(c){b=!1}}else if(window.XMLHttpRequest)try{b=new XMLHttpRequest}catch(d){b=!1}return b},load:function(b,a,c,d,f){var e=this.init();if(e&&b){e.overrideMimeType&&e.overrideMimeType("text/xml");d||(d="GET");c||(c="text");
f||(f={});c=c.toLowerCase();d=d.toUpperCase();var h="uid\x3d"+(new Date).getTime();b+=b.indexOf("?")+1?"\x26":"?";b+=h;h=null;"POST"==d&&(h=b.split("?"),b=h[0],h=h[1]);e.open(d,b,!0);"POST"==d&&(e.setRequestHeader("Content-type","application/x-www-form-urlencoded"),e.setRequestHeader("Content-length",h.length),e.setRequestHeader("Connection","close"));e.onreadystatechange=f.handler?function(){f.handler(e)}:function(){if(4==e.readyState)if(200==e.status){var b="";e.responseText&&(b=e.responseText);
"j"==c.charAt(0)?(b=b.replace(/[\n\r]/g,""),b=eval("("+b+")")):"x"==c.charAt(0)&&(b=e.responseXML);a&&a(b)}else f.loadingIndicator&&document.getElementsByTagName("body")[0].removeChild(f.loadingIndicator),f.loading&&(document.getElementById(f.loading).style.display="none"),error&&error(e.status)};e.send(h)}},bind:function(b){var a={url:"",onSuccess:!1,onError:!1,format:"text",method:"GET",update:"",loading:"",loadingIndicator:""},c;for(c in a)b[c]&&(a[c]=b[c]);if(a.url){var d=!1;a.loadingIndicator&&
(d=document.createElement("div"),d.setAttribute("style","position:absolute;top:0px;left:0px;"),d.setAttribute("class","loading-indicator"),d.innerHTML=a.loadingIndicator,document.getElementsByTagName("body")[0].appendChild(d),this.opt.loadingIndicator=d);a.loading&&(document.getElementById(a.loading).style.display="block");this.load(a.url,function(b){if(a.onSuccess)a.onSuccess(b);a.update&&(document.getElementById(a.update).innerHTML=b);d&&document.getElementsByTagName("body")[0].removeChild(d);a.loading&&
(document.getElementById(a.loading).style.display="none")},a.format,a.method,a)}},init:function(){return this.getHTTPObject()}}});
function mad_expandableImage_open(b,a){if(0==document.getElementById(a).style.opacity){var c=madApi.position(document.getElementById(b)),d=madApi.size(document.getElementById(b)),f=madApi.getWindowSize(),e,h;e=c.top;h=c.left+d.width;300>f.width-(c.left+d.width)&&(e=c.top,h=c.left-300);document.getElementById(a).style.left=h+"px";document.getElementById(a).style.top=e+"px";madApi.isIE(0)?document.getElementById(a).style.opacity=1:madApi.fx(document.getElementById(a)).fxAdd({type:"opacity",from:0,to:100,
step:10,delay:10}).fxRun(null,1)}}function mad_expandableImage_close(b){0!=document.getElementById(b).style.opacity&&(madApi.isIE(0)?document.getElementById(b).style.opacity=0:madApi.fx(document.getElementById(b)).fxAdd({type:"opacity",from:100,to:0,step:10,delay:10}).fxRun(null,1))};