"object"!==typeof JSON&&(JSON={});
(function(){function a(a){return 10>a?"0"+a:a}function b(a){h.lastIndex=0;return h.test(a)?'"'+a.replace(h,function(a){var b=r[a];return"string"===typeof b?b:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function e(a,d){var f,n,l,h,q=g,k,c=d[a];c&&("object"===typeof c&&"function"===typeof c.toJSON)&&(c=c.toJSON(a));"function"===typeof m&&(c=m.call(d,a,c));switch(typeof c){case "string":return b(c);case "number":return isFinite(c)?String(c):"null";case "boolean":case "null":return String(c);
case "object":if(!c)return"null";g+=p;k=[];if("[object Array]"===Object.prototype.toString.apply(c)){h=c.length;for(f=0;f<h;f+=1)k[f]=e(f,c)||"null";l=0===k.length?"[]":g?"[\n"+g+k.join(",\n"+g)+"\n"+q+"]":"["+k.join(",")+"]";g=q;return l}if(m&&"object"===typeof m)for(h=m.length,f=0;f<h;f+=1)"string"===typeof m[f]&&(n=m[f],(l=e(n,c))&&k.push(b(n)+(g?": ":":")+l));else for(n in c)Object.prototype.hasOwnProperty.call(c,n)&&(l=e(n,c))&&k.push(b(n)+(g?": ":":")+l);l=0===k.length?"{}":g?"{\n"+g+k.join(",\n"+
g)+"\n"+q+"}":"{"+k.join(",")+"}";g=q;return l}}"function"!==typeof Date.prototype.toJSON&&(Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+a(this.getUTCMonth()+1)+"-"+a(this.getUTCDate())+"T"+a(this.getUTCHours())+":"+a(this.getUTCMinutes())+":"+a(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()});var d=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
h=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,g,p,r={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},m;"function"!==typeof JSON.stringify&&(JSON.stringify=function(a,b,f){var d;p=g="";if("number"===typeof f)for(d=0;d<f;d+=1)p+=" ";else"string"===typeof f&&(p=f);if((m=b)&&"function"!==typeof b&&("object"!==typeof b||"number"!==typeof b.length))throw Error("JSON.stringify");return e("",{"":a})});
"function"!==typeof JSON.parse&&(JSON.parse=function(a,b){function f(a,d){var e,g,c=a[d];if(c&&"object"===typeof c)for(e in c)Object.prototype.hasOwnProperty.call(c,e)&&(g=f(c,e),void 0!==g?c[e]=g:delete c[e]);return b.call(a,d,c)}var e;a=String(a);d.lastIndex=0;d.test(a)&&(a=a.replace(d,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return e=eval("("+a+")"),"function"===typeof b?f({"":e},""):e;throw new SyntaxError("JSON.parse");})})();"undefined"==typeof AdLytics&&(AdLytics={insertScript:function(a){var b=document.createElement("script");b.type="text/javascript";b.async=!0;b.src=a;(document.getElementsByTagName("head")[0]||document.body).appendChild(b)},onload:function(a){var b=window.onload;window.onload="function"!=typeof window.onload?a:function(){b();a()}},delegate:function(a,b,e){var d=e||arguments,h=function(){return a.apply(arguments.callee.target,d)};h.target=b;h.func=this;return h},position:function(a){var b=0,e=0;if(a.offsetParent){do b+=
a.offsetLeft,e+=a.offsetTop;while(a=a.offsetParent)}return{left:b,top:e}},size:function(a){return{height:a.offsetHeight,width:a.offsetWidth}},getWindowSize:function(){var a=0,b=0;"number"==typeof window.innerWidth?(a=window.innerWidth,b=window.innerHeight):document.documentElement&&(document.documentElement.clientWidth||document.documentElement.clientHeight)?(a=document.documentElement.clientWidth,b=document.documentElement.clientHeight):document.body&&(document.body.clientWidth||document.body.clientHeight)&&
(a=document.body.clientWidth,b=document.body.clientHeight);return{width:a,height:b}},getScrollXY:function(a){var b=a=0;"number"==typeof window.pageYOffset?(b=window.pageYOffset,a=window.pageXOffset):document.body&&(document.body.scrollLeft||document.body.scrollTop)?(b=document.body.scrollTop,a=document.body.scrollLeft):document.documentElement&&(document.documentElement.scrollLeft||document.documentElement.scrollTop)&&(b=document.documentElement.scrollTop,a=document.documentElement.scrollLeft);return{x:a,
y:b}},addEvent:function(a,b,e,d){a.attachEvent?a.attachEvent("on"+b,e):(d||(d=!1),a.addEventListener(b,e,d))},ajax:{getHTTPObject:function(){var a=!1;if("undefined"!=typeof ActiveXObject)try{a=new ActiveXObject("Msxml2.XMLHTTP")}catch(b){try{a=new ActiveXObject("Microsoft.XMLHTTP")}catch(e){a=!1}}else if(window.XMLHttpRequest)try{a=new XMLHttpRequest}catch(d){a=!1}return a},post:function(a,b,e){var d=AdLytics.ajax.getHTTPObject();d&&a&&(d.open("POST",a),d.setRequestHeader("Content-Type","application/json;charset\x3dUTF-8"),
d.send(JSON.stringify(e)),d.onreadystatechange=function(){b()})}}});